---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
# - Launchpad
 - TV
 - Contacts
 - Notes
 - Freeform
 - Podcasts
 - Messages
 - Maps
 - Photos
 - 'App Store'
dockitems_persist:
- name: "Brave"
  path: "/Applications/Brave Browser.app/"
  pos: 1
- name: "Firefox"
  path: "/Applications/Firefox.app/"
  pos: 2
- name: "Safari"
  path: "/Applications/Safari.app/"
  pos: 3
- name: "VS Code"
  path: "/Applications/Visual Studio Code.app/"
  pos: 4
- name: "iTerm2"
  path: "/Applications/iTerm.app/"
  pos: 5
- name: "Slack"
  path: "/Applications/Slack.app/"
  pos: 6

configure_sudoers: false
# Option A: (MacOS Sonoma 14.3+ only) Sudo via fingerprint/yubikey, see /etc/pam.d/sudo_local.template
use_sudo_local: true # Sonoma+ only!
sudo_local_config: |
  # sudo_local: local config file which survives system update and is included for sudo
  # uncomment following line to enable Touch ID for sudo
  auth       sufficient     pam_tid.so
  # yubikey auth can be added here as well
# Option B: Generic sudoers, using /private/etc/sudoers.d/custom
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: git@github.com:excalq/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/code/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - act # Github Actions local CLI
  - asdf # Dev tools version manager
  - autoconf
  - bash-completion
  - cowsay 
  - diff-so-fancy # Better git diffs
  - docker-compose
  - doxygen
  - gettext
  - gh # Github CLI
  - gifsicle
  - git
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - minikube
  - neovim
  - nmap
  - node
  - nvm
  - openssl
  - pv # Pipe Viewer (progress bars)
  - readline
  - sqlite
  - ssh-copy-id
  - starship # Beautiful prompts
  - virtualenv
  - wget
  - wrk # HTTP benchmarking tool
  - yarn
  - zsh-history-substring-search

homebrew_taps: []

# Warning: Remove/rename manually installed Apps before adding those here, avoiding permission errors
homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - brave-browser
  - discord
  - docker
  - firefox
  - font-hack-nerd-font
  - font-hasklug-nerd-font
  - font-ubuntu-mono-nerd-font
  - handbrake
  - sequel-ace
  - slack
  - transmit

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages:
- name: slither
- name: click
- name: jupyterlab
- name: pandas
- name: tqdm
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure VS Code. See https://github.com/gantsign/ansible-role-visual-studio-code
configure_vscode: true
visual_studio_code_config_path: 
vscode_user_config:
  - username: arthur
    visual_studio_code_extensions:
      - ms-python.python
      - streetsidesoftware.code-spell-checker
      - redhat.ansible
      - wholroyd.jinja
      - hashicorp.terraform
      - github.copilot

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
